import { StyleSheet } from "react-native";

export const crmStyles = StyleSheet.create({
  container: { gap: 14 },
  overviewCard: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fbcfe8",
    borderRadius: 20,
    padding: 16,
  },
  overviewTitle: { fontSize: 20, fontWeight: "900", color: "#1e293b" },
  overviewSubtitle: { fontSize: 13, color: "#64748b", marginTop: 4, lineHeight: 18 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statCard: {
    flexGrow: 1,
    minWidth: 130,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#f1e5f9",
    borderRadius: 16,
    padding: 12,
  },
  statLabel: { fontSize: 11, fontWeight: "bold", color: "#94a3b8", textTransform: "uppercase" },
  statValue: { fontSize: 20, fontWeight: "900", marginTop: 4 },
  toolbar: { flexDirection: "row", gap: 8, alignItems: "center" },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 14,
    paddingHorizontal: 12,
  },
  searchInput: { flex: 1, paddingVertical: 8, fontSize: 13, color: "#334155" },
  refreshButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fbcfe8",
    alignItems: "center",
    justifyContent: "center",
  },
  tabsRow: { flexDirection: "row", gap: 6 },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e9d5ff",
    backgroundColor: "#fff",
    alignItems: "center",
  },
  tabButtonActive: { backgroundColor: "#9333ea", borderColor: "#9333ea" },
  tabButtonText: { fontSize: 12, fontWeight: "bold", color: "#64748b", textTransform: "uppercase" },
  tabButtonTextActive: { color: "#fff" },
  filtersRow: { paddingVertical: 4 },
  filterPill: {
    marginRight: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#e9d5ff",
    backgroundColor: "#fff",
  },
  filterPillActive: { backgroundColor: "#ec4899", borderColor: "#ec4899" },
  filterPillText: { fontSize: 11, fontWeight: "700", color: "#475569" },
  filterPillTextActive: { color: "#fff" },
  emptyText: {
    textAlign: "center",
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "bold",
    marginVertical: 24,
  },
  leadRowMobile: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 8,
  },
  leadRowMobileActive: {
    borderColor: "#ec4899",
  },
  badgeTextMini: {
    fontSize: 9,
    fontWeight: "bold",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    overflow: "hidden",
  },
  tableBorder: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 12,
    overflow: "hidden",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  tableHeaderCol: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#64748b",
  },
  leadRowWeb: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#cbd5e1",
    paddingVertical: 8,
    paddingHorizontal: 12,
    minHeight: 56,
  },
  rowCol: {
    justifyContent: "center",
  },
  rowText: {
    fontSize: 12,
    color: "#334155",
  },
  rowTextBold: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#1e293b",
  },
  rowTextSmall: {
    fontSize: 11,
    color: "#94a3b8",
  },
  btnDetailCompact: {
    backgroundColor: "#ec4899",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  btnDetailCompactText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#fff",
  },
  pillButton: {
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  pillButtonText: { fontSize: 11, fontWeight: "bold", color: "#475569" },
  paginationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  pageBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  pageBtnText: { fontSize: 11, fontWeight: "bold", color: "#475569" },
  pageLabel: { fontSize: 11, color: "#64748b", fontWeight: "bold" },
  kanbanColumn: {
    width: 260,
    marginRight: 10,
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 10,
    maxHeight: 500,
  },
  kanbanHeader: { fontSize: 13, fontWeight: "800" },
  kanbanCount: { fontSize: 11, fontWeight: "bold", color: "#94a3b8" },
  kanbanEmpty: { textAlign: "center", color: "#cbd5e1", fontSize: 11, paddingVertical: 32 },
  kanbanCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 8,
    gap: 4,
  },
  kanbanCardActive: {
    borderColor: "#ec4899",
  },
  kanbanCardName: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1e293b",
  },
  kanbanCardText: {
    fontSize: 11,
    color: "#64748b",
  },
  kanbanCardTextBold: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#1e293b",
  },
  kanbanCardSmall: {
    fontSize: 10,
    color: "#94a3b8",
  },
  kanbanCardBtn: {
    alignSelf: "flex-start",
    backgroundColor: "#9333ea",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 4,
  },
  kanbanCardBtnText: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#fff",
  },
  detailWrap: { gap: 14 },
  detailInfoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  detailName: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1e293b",
    marginBottom: 12,
  },
  detailInfoGrid: {
    gap: 8,
  },
  detailInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailInfoText: {
    fontSize: 12,
    color: "#475569",
  },
  selectLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#64748b",
    marginBottom: 4,
  },
  detailSection: { borderTopWidth: 1, borderTopColor: "#f1f5f9", paddingTop: 12 },
  detailSectionTitle: { fontSize: 13, fontWeight: "800", color: "#1e293b", marginBottom: 6 },
  tealActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#14b8a6",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  greenActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#22c55e",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionBtnText: { fontSize: 11, fontWeight: "bold", color: "#fff" },
  overrideSection: {
    borderWidth: 1,
    borderColor: "#fed7aa",
    backgroundColor: "#fff7ed",
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  overrideTitle: { fontSize: 13, fontWeight: "900", color: "#ea580c" },
  overrideSub: { fontSize: 11, color: "#c2410c", lineHeight: 16 },
  formInput: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12,
    color: "#334155",
  },
  checkboxBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#ea580c",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxLabel: { fontSize: 11, fontWeight: "bold", color: "#c2410c" },
  overrideSubmit: {
    backgroundColor: "#ea580c",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  overrideSubmitText: { fontSize: 11, fontWeight: "900", color: "#fff" },
  btnPink: {
    backgroundColor: "#ec4899",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
    alignSelf: "flex-start",
    paddingHorizontal: 16,
  },
  btnPinkText: { fontSize: 11, fontWeight: "900", color: "#fff" },
  noteBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    padding: 8,
    borderWidth: 1,
    borderColor: "#f1f5f9",
  },
  noteText: { fontSize: 12, color: "#334155", lineHeight: 16 },
  noteMeta: { fontSize: 9, color: "#94a3b8", marginTop: 4 },
});