import { StyleSheet } from "react-native";

export const affiliateStyles = StyleSheet.create({
  container: { gap: 20 },
  statsRow: { flexDirection: "row", gap: 16, flexWrap: "wrap" },
  statCard: {
    flex: 1,
    minWidth: 200,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "#f1e6eb",
  },
  statLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  statValue: { fontSize: 24, fontWeight: "900", color: "#1e1b20", marginTop: 8 },
  subTabs: { flexDirection: "row", backgroundColor: "#f1f5f9", borderRadius: 16, padding: 4 },
  subTabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 12,
  },
  subTabText: { fontSize: 13, fontWeight: "bold", color: "#64748b" },
  subTabTextActive: { color: "#1e1b20" },
  errorBanner: {
    backgroundColor: "#fef2f2",
    borderColor: "#fee2e2",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
  },
  errorText: { color: "#991b1b", fontSize: 13, fontWeight: "bold" },
  sectionGap: { gap: 24 },
  formCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    gap: 16,
  },
  formTitle: { fontSize: 18, fontWeight: "bold", color: "#1e1b20" },
  formRow: { flexDirection: "row", gap: 16, flexWrap: "wrap" },
  formInput: {
    flex: 1,
    minWidth: 200,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 16,
  },
  formInputCode: {
    flex: 1,
    minWidth: 200,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 16,
    fontWeight: "bold",
  },
  formInputSmall: {
    flex: 1,
    minWidth: 120,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 16,
  },
  commissionToggle: {
    flexDirection: "row",
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    overflow: "hidden",
    height: 44,
  },
  commissionToggleBtn: { paddingHorizontal: 16, justifyContent: "center" },
  commissionToggleText: { fontSize: 12, fontWeight: "bold", color: "#64748b" },
  divider: { height: 1, backgroundColor: "#f1e6eb", marginVertical: 8 },
  bankSectionTitle: { fontSize: 14, fontWeight: "bold", color: "#1e1b20" },
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: 10, marginTop: 8 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxLabel: { fontSize: 13, color: "#475569", fontWeight: "500" },
  submitButton: {
    height: 48,
    borderRadius: 16,
    backgroundColor: "#ec4899",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  submitButtonText: { fontSize: 14, fontWeight: "bold", color: "#fff" },
  listTitle: { fontSize: 18, fontWeight: "bold", color: "#1e1b20" },
  listGap: { gap: 12 },
  affiliateCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    padding: 20,
  },
  affiliateName: { fontSize: 16, fontWeight: "bold", color: "#1e1b20" },
  affiliateContact: { fontSize: 13, color: "#64748b" },
  codeBadge: {
    backgroundColor: "#fce7f3",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  codeBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#db2777",
    fontFamily: "monospace",
  },
  commissionText: { fontSize: 12, fontWeight: "bold", color: "#ec4899" },
  toggleBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  toggleBtnText: { fontSize: 11, fontWeight: "bold" },
  expandedSection: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#f1e6eb",
    gap: 8,
  },
  expandedLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
  },
  expandedText: { fontSize: 13, color: "#1e1b20" },
  expandedMuted: { fontSize: 13, color: "#94a3b8", fontStyle: "italic" },
  expandedMeta: { fontSize: 11, color: "#94a3b8", marginTop: 4 },
  conversionCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    padding: 20,
  },
  conversionBuyer: { fontSize: 14, fontWeight: "bold", color: "#1e1b20" },
  conversionEmail: { fontSize: 12, color: "#64748b" },
  conversionAmount: { fontSize: 16, fontWeight: "900", color: "#10b981" },
  conversionPaidFrom: { fontSize: 11, color: "#94a3b8" },
  affiliateInfoBox: {
    backgroundColor: "#f8fafc",
    padding: 12,
    borderRadius: 12,
    gap: 4,
  },
  affiliateInfoTitle: { fontSize: 12, fontWeight: "bold", color: "#64748b" },
  affiliateInfoText: { fontSize: 12, color: "#475569" },
  payoutRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  payoutStatusRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  payoutDot: { width: 8, height: 8, borderRadius: 4 },
  payoutStatusText: { fontSize: 12, fontWeight: "bold" },
  markPaidButton: {
    backgroundColor: "#ec4899",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  markPaidText: { fontSize: 11, fontWeight: "bold", color: "#fff" },
  payoutReference: { fontSize: 11, color: "#64748b", marginTop: 8 },
});