import { StyleSheet } from "react-native";

export const whatsappStyles = StyleSheet.create({
  container: { gap: 24 },
  introCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    gap: 6,
  },
  introTitle: { fontSize: 16, fontWeight: "bold", color: "#1e1b20" },
  introSubtitle: { fontSize: 13, color: "#64748b", lineHeight: 18 },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#475569",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  editorCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    padding: 20,
    gap: 16,
  },
  editorTitle: { fontSize: 16, fontWeight: "bold", color: "#1e1b20" },
  toggleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  toggleTitle: { fontSize: 14, fontWeight: "bold", color: "#1e1b20" },
  toggleSubtitle: { fontSize: 12, color: "#64748b" },
  toggleTrack: {
    width: 52,
    height: 32,
    borderRadius: 16,
    padding: 2,
    justifyContent: "center",
  },
  toggleThumb: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  fieldLabel: { fontSize: 13, fontWeight: "bold", color: "#475569" },
  fieldHint: { fontSize: 11, color: "#94a3b8" },
  delayInput: {
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 16,
    fontSize: 13,
    color: "#1e1b20",
  },
  placeholderChip: {
    backgroundColor: "#faf5f8",
    borderWidth: 1,
    borderColor: "#fce7f3",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  placeholderChipText: {
    fontSize: 11,
    color: "#ec4899",
    fontFamily: "monospace",
    fontWeight: "bold",
  },
  templateInput: {
    minHeight: 180,
    borderRadius: 16,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    fontSize: 13,
    color: "#334155",
    textAlignVertical: "top",
    lineHeight: 18,
  },
  previewPanel: {
    backgroundColor: "#fafafb",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    padding: 16,
    gap: 8,
  },
  previewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  previewTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
  },
  warningText: { fontSize: 12, color: "#d97706", fontWeight: "500", fontStyle: "italic" },
  previewBox: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
  },
  previewText: { fontSize: 13, color: "#334155", lineHeight: 18 },
  testPanel: {
    backgroundColor: "#faf5f8",
    borderWidth: 1,
    borderColor: "#fce7f3",
    borderRadius: 16,
    padding: 16,
    gap: 10,
  },
  testTitle: { fontSize: 13, fontWeight: "bold", color: "#1e1b20" },
  testPhoneInput: {
    flex: 1,
    minWidth: 180,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#fce7f3",
    paddingHorizontal: 12,
    fontSize: 13,
    color: "#1e1b20",
  },
  testSendButton: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  testSendButtonText: { fontSize: 12, fontWeight: "bold", color: "#fff" },
  actionRow: { flexDirection: "row", gap: 12, marginTop: 4 },
  resetButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  resetButtonText: { fontSize: 13, fontWeight: "bold", color: "#64748b" },
  saveButton: {
    flex: 2,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#ec4899",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButtonText: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#fff",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  logsCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#f1e6eb",
    padding: 20,
    gap: 16,
  },
  logsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 10,
  },
  logsTitle: { fontSize: 16, fontWeight: "bold", color: "#1e1b20" },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#faf5f8",
    alignItems: "center",
    justifyContent: "center",
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#94a3b8",
    textTransform: "uppercase",
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  filterChipText: { fontSize: 11, fontWeight: "bold" },
  emptyLogsText: { fontSize: 13, color: "#94a3b8", fontWeight: "bold" },
  logCard: {
    backgroundColor: "#fcf8fa",
    borderWidth: 1,
    borderColor: "#f1e6eb",
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  logEventLabel: { fontSize: 11, fontWeight: "bold", color: "#9333ea" },
  logRecipientName: { fontSize: 13, fontWeight: "bold", color: "#1e1b20" },
  logRecipientPhone: { fontSize: 11, color: "#64748b", fontFamily: "monospace" },
  logMessageBox: {
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#f1e6eb",
  },
  logMessageText: { fontSize: 12, color: "#334155", lineHeight: 16 },
  expandLink: { fontSize: 11, color: "#ec4899", fontWeight: "bold" },
  errorBox: {
    backgroundColor: "#fef2f2",
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#fee2e2",
  },
  errorTitle: { fontSize: 11, color: "#ef4444", fontWeight: "bold" },
  errorText: { fontSize: 11, color: "#b91c1c", marginTop: 2 },
  skippedBox: {
    backgroundColor: "#f8fafc",
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  skippedTitle: { fontSize: 11, color: "#475569", fontWeight: "bold" },
  skippedText: { fontSize: 11, color: "#64748b", marginTop: 2 },
  logMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  logMetaText: { fontSize: 10, color: "#94a3b8" },
  metadataLink: { fontSize: 10, color: "#64748b", textDecorationLine: "underline" },
  metadataBox: {
    backgroundColor: "#f1f5f9",
    padding: 10,
    borderRadius: 10,
    marginTop: 4,
  },
  metadataLabel: { fontSize: 10, fontWeight: "bold", color: "#475569" },
  metadataValue: { fontSize: 10, color: "#475569", fontFamily: "monospace", marginVertical: 2 },
  loadingContainer: { paddingVertical: 48, alignItems: "center", justifyContent: "center" },
  loadingText: { marginTop: 12, color: "#64748b", fontSize: 13 },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  statusBadgeText: { fontSize: 10, fontWeight: "bold", textTransform: "uppercase" },
});